pipelines:
  - name: Test_automation_parallel_u18_env
    steps:
      - name: setup_tests
        type: Bash
        configuration:
          integrations:
            - name: github
          inputResources:
            - name: auto_gitRepo
              trigger: False
        execution:
          onStart:
            - echo "test"


